# Generated by Django 6.1 on 2026-10-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Delivered', 'delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
